### ISSUE TITLE
error: more than one device/emulator

### ISSUE THREAD

**Issue by kazemihabib** [NathanaelA/nativescript-liveedit#20]
I got this error:

```
NativeScript LiveEdit Watcher v0.13
(c)2015, 2016, Master Technology.  www.master-technology.com
------------------------------------------------------------
Watching your project: org.nativescript.groceries
error: more than one device/emulator
Error: error: more than one device/emulator
 38
```

**Comment by NathanaelA** [comment]
Yeah, this occurs if you have more than one Android device/emulator connected to the computer.   At this point LiveEdit doesn't attempt to pass a device id, so you get this error.

I have not decided how I want to fix this issue; I can do:
- Send changes to all emulators
- Allow you to pick a emulator

However since this is more of a corner case, at this moment this is a fairly low priority for me.  I do accept pull requests and/or bounties to fix those items that are not high on my priority list.

**Comment by kazemihabib** [comment]
but I don't have more than one emulator, I just have a genymotion emulator.
Edit:
I checked with tns device and it seems that I have more than one emulator but I don't know where is the second one.
iTunes is not installed. Install it on your system and run this command again.
┌───┬─────────────┬──────────┬──────────────────────┬──────────┬───────────┐
│ # │ Device Name │ Platform │ Device Identifier    │ Type     │ Status    │
│ 1 │ vbox86p     │ Android  │ 192.168.230.101:5555 │ Emulator │ Connected │
│ 2 │             │ Android  │ emulator-5604        │ Device   │ host      │
└───┴─────────────┴──────────┴──────────────────────┴──────────┴───────────┘

**Comment by kazemihabib** [comment]
I had delete the emulator from android studio avd but it was running in the background so I did `adb kill-server` and the problem fixed.
